name: "Build and push image"
description: "Builds and pushes an image to a registry"

inputs:
  service:
    description: "Service to build"
    required: true
  registry_host:
    description: "Image registry host e.g. myacr.azureacr.io"
    required: true
  registry_endpoint:
    description: "Image registry repo e.g. myacr.azureacr.io/eshop"
    required: true
  image_name:
    description: "Name of image"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Compose build ${{ inputs.service }}
      shell: bash
      run: sudo -E docker-compose -f docker-compose-build.yaml build ${{ inputs.service }}
      working-directory: .

    - name: Docker Tag ${{ inputs.service }}
      shell: bash
      run: sudo -E docker tag ${{ inputs.service }} -t ${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:latest
      working-directory: ./src/services

    - name: Compose push ${{ inputs.service }}
      shell: bash
      run: sudo -E docker push ${{ inputs.service }}
