name: "Build and push image"
description: "Builds and pushes an image to a registry"

inputs:
  service:
    description: "Service to build"
    required: true
  registry_host:
    description: "Image registry host e.g. myacr.azureacr.io"
    required: true
  registry_endpoint:
    description: "Image registry repo e.g. myacr.azureacr.io/eshop"
    required: true
  image_name:
    description: "Name of image"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setting environment variables
      id: get_env
      shell: bash
      run: |
        TMP_GITHUB_COMMITS_COUNT=$(git rev-list --count HEAD)
        TMP_GITHUB_COUNT_NUMBER=$(echo ${GITHUB_RUN_NUMBER})
        echo "::set-output name=GITHUB_SHA::$(echo ${GITHUB_SHA::8})"
        echo "::set-output name=RELEASE_VERSION::1.$TMP_GITHUB_COMMITS_COUNT.$TMP_GITHUB_COUNT_NUMBER"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Compose build ${{ inputs.service }}
      shell: bash
      run: sudo -E docker build . -t ${{ inputs.service }}

    - name: Docker Tag ${{ inputs.service }}
      shell: bash
      run: |
        sudo -E docker tag ${{ inputs.service }} ${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:${{ steps.get_env.outputs.GITHUB_SHA }}
        sudo -E docker tag ${{ inputs.service }} ${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:${{ steps.get_env.outputs.RELEASE_VERSION }}
        sudo -E docker tag ${{ inputs.service }} ${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:latest

    - name: Compose push ${{ inputs.service }}
      shell: bash
      run: sudo -E docker push ${{ inputs.service }}
