name: "Build, test and deploy the Blob API"

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - src/services/Blob/**
      - .github/workflows/blob.api.yml

env:
  SERVICE: blob
  IMAGE_NAME: blob-service

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: src/services/Blob

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.working-directory}}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.working-directory}}

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{env.working-directory}}

      - name: Build & push container image
        uses: ./.github/workflows/composite
        with:
          service: ${{ env.SERVICE }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          image_name: ${{ env.IMAGE_NAME }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
