name: blob-api

on:
  workflow_dispatch:
  push:
    branches: [master, dev]
    paths:
      - src/services/Blob/**
      - .github/workflows/blob-api.yml

env:
  SERVICE: blob-api
  IMAGE: blob.api

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: src/services/Blob

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.working-directory}}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.working-directory}}

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{env.working-directory}}
