name: "Build, test and deploy the Media API"

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - src/services/Media/**
      - .github/workflows/media.api.yml

env:
  SERVICE: media
  DOCKER_IMAGE: docker.io/rahalh/media

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: src/services/Media

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setting environment variables
        id: get_env
        run: |
          TMP_GITHUB_COMMITS_COUNT=$(git rev-list --count HEAD)
          TMP_GITHUB_COUNT_NUMBER=$(echo ${GITHUB_RUN_NUMBER})
          echo "::set-output name=GITHUB_SHA::$(echo ${GITHUB_SHA::8})"
          echo "::set-output name=RELEASE_VERSION::1.$TMP_GITHUB_COMMITS_COUNT.$TMP_GITHUB_COUNT_NUMBER"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.working-directory}}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.working-directory}}

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{env.working-directory}}

      - name: Prepare for push
        id: prep
        run: |
          TAGS="${{ env.DOCKER_IMAGE }}:${{ steps.prepare.outputs.GITHUB_SHA }},${{ env.DOCKER_IMAGE }}:${{ steps.prepare.outputs.RELEASE_VERSION }},${{ env.DOCKER_IMAGE }}:latest"
          echo ::set-output name=tags::${TAGS}

      - name: Build & push container image
        uses: ./.github/workflows/composite
        with:
          service: ${{ env.SERVICE }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          image_name: ${{ env.DOCKER_IMAGE }}
          image_tags: ${{ steps.prep.outputs.tags }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
